package dataGenerator;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

/**
 * class to load signal files in resources folder generated by MATLAB
 * There are normal and abnormal signal pieces for each type.
 */
public class Data {
    /**
     * method to load signal files
     * @param filename filename to load
     * @return values in the file
     */
    public List<Double> loadFile(String filename){
        List<Double> values = new ArrayList();
        String line;
        //load the file from resources folder
        InputStream inputStream = getClass().getClassLoader().getResourceAsStream(filename+".csv");
        InputStreamReader streamReader = new InputStreamReader(inputStream);
        try (BufferedReader br = new BufferedReader(streamReader)) {
            while((line = br.readLine()) != null){
                values.add(Double.valueOf(line));
            }
        } catch (Exception ignored){}
        return values;
    }
}